# Configuration for CircleCI
version: 2.1
orbs:
  matlab: mathworks/matlab@0.3.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          name: "Switch to Python 3.7"
          command: |
            pyenv versions
            pyenv global 3.7.0
      - matlab/install
      - matlab/run-command:
          command: addpath dev-kit; launchtests_mypackage
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
          code-coverage-cobertura: coverage
          source-folder: Mcode
      - store_test_results:
          path: test-results
      - run:
          command: make test
      - run:
          command: make dist
      - run:
          command: make clean
      - run:
          command: ./MatlabProjectTemplate/test_project_initialization
